#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# a custom header
#
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 26071-web-01 44.192.84.176:80 check
    server 26071-web-02 44.200.144.73:80 check
"
# Update packages
sudo apt update
sudo apt upgrade

# Add HAProxy PPA
sudo apt install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.5
sudo apt update

# Install HAProxy
sudo apt install haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
